version: '3'
services:
  mysql:
    image: mysql:8.2.0
    container_name: incidentapi.mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: incidentapi
    ports:
      - "3306:3306"
    volumes:
      - /path/to/mysql/data:/var/lib/mysql
  flyway:
    image: boxfuse/flyway
    container_name: incidentapi.flyway
    command: ["-url=jdbc:mysql://mysql:3306/incidentapi", "-schemas=incident-api", "-user=root", "-connectRetries=120", "-password=root", "migrate"]
    depends_on:
      - mysql
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
