spring:
  jpa:
    hibernate:
    show-sql: true
    ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/incidentapi
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
